{% set name = "cma" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf0621d4f52cf3354be3d0a5cd439ffed52f24f429ab02c23cf0f8ca16d427d8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - numpy
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - cma
    - cma.utilities

about:
  home: https://github.com/CMA-ES/pycma
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CMA-ES, Covariance Matrix Adaptation Evolution Strategy for non-linear numerical optimization in Python
  doc_url: http://cma.gforge.inria.fr/apidocs-pycma/
  description: |
    The Covariance Matrix Adaptation Evolution Strategy (CMA-ES) is a stochastic derivative-free numerical 
    optimization algorithm for difficult (non-convex, ill-conditioned, multi-modal, rugged, noisy) optimization
    problems in continuous search spaces.
extra:
  recipe-maintainers:
    - rpanai
